name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Логин в GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Собираем и пушим образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/flask-cicd-demo:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/flask-cicd-demo:latest

      # 5. Деплой на сервер через SSH
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/flask-cicd-demo
            docker pull ghcr.io/${{ github.repository_owner }}/flask-cicd-demo:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d --name flask-app -p 5000:5000 ghcr.io/${{ github.repository_owner }}/flask-cicd-demo:latest